spring:
    datasource:
        url: jdbc:h2:mem:testdb
        username: sa
        password:
        platform: h2
        hikari:
            connection-test-query: SELECT 1
        initialization-mode: always
    jpa:
        database: H2
        show-sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: validate

    flyway:
        baseline-on-migrate: true
        validate-on-migrate: true

