spring:
  datasource:
    url: ${DATABASE__URL}
    username: ${USER_NAME}
    password: ${PASSWORD}
    platform: postgres
    hikari:
      connection-test-query: SELECT 1
  jpa:
    database-platform: com.store.book.MyH2Dialect
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate

  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true

